val = ValueError("This is a test throw")

raise val
